CREATE OR REPLACE TRIGGER trg_update_default_address
AFTER UPDATE OF ISDEFAULT ON SHOP_ADDRESS
FOR EACH ROW
BEGIN
    IF :NEW.ISDEFAULT = 'Y' THEN
        UPDATE SHOP_ADDRESS
        SET ISDEFAULT = 'N', LAST_UPDATE = SYSDATE
        WHERE MEMBER_SEQ = :NEW.MEMBER_SEQ AND ISDEFAULT = 'Y';
    END IF;
END;
/