CREATE SEQUENCE GOODS_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

CREATE TABLE Shop_goods (
    GOODS_SEQ NUMBER(10, 0) PRIMARY KEY,
    GNAME NVARCHAR2(10) NOT NULL,
    PRICE NUMBER(10, 0) NOT NULL,
    QUANTITY NUMBER(3, 0) NOT NULL,
    INFORMATION NVARCHAR2(1000),
    TITLE_IMG NVARCHAR2(1000),
    INFO_IMG NVARCHAR2(1000),
    UPLOAD_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE
);

DROP TABLE Shop_goods;
DROP SEQUENCE GOODS_SEQ;

INSERT INTO Shop_Goods (GOODS_SEQ, GNAME, PRICE, QUANTITY, INFORMATION) VALUES (GOODS_SEQ.NEXTVAL, '테스트1', '10000', '100', '테스트 상품 설명입니다');

SELECT * FROM Shop_goods;