CREATE TABLE Shop_goods (
    GNO NUMBER(10, 0) PRIMARY KEY, --일련번호
    GNAME NVARCHAR2(100) NOT NULL, --상품명
    PRICE NUMBER(10, 0) NOT NULL, --가격
    QUANTITY NUMBER(3, 0) NOT NULL, --수량
    INFORMATION NVARCHAR2(1000), --정보설명
    TITLE_IMG NVARCHAR2(1000), --제목 이미지
    INFO_IMG NVARCHAR2(1000), --정보 이미지
    UPLOAD_DATE DATE DEFAULT SYSDATE, --업로드일
    UPDATE_DATE DATE DEFAULT SYSDATE --수정일
);

DROP TABLE Shop_goods;

INSERT INTO Shop_Goods (GNO, GNAME, PRICE, QUANTITY, INFORMATION) VALUES ('1', '테스트1', '10000', '100', '테스트1 상품 설명입니다');
INSERT INTO Shop_Goods (GNO, GNAME, PRICE, QUANTITY, INFORMATION) VALUES ('2', '테스트2', '20000', '200', '테스트2 상품 설명입니다');
INSERT INTO Shop_Goods (GNO, GNAME, PRICE, QUANTITY, INFORMATION) VALUES ('3', '테스트3', '30000', '300', '테스트3 상품 설명입니다');
INSERT INTO Shop_Goods (GNO, GNAME, PRICE, QUANTITY, INFORMATION) VALUES ('4', '테스트4', '40000', '400', '테스트4 상품 설명입니다');
INSERT INTO Shop_Goods (GNO, GNAME, PRICE, QUANTITY, INFORMATION) VALUES ('5', '테스트5', '550000', '500', '테스트5 상품 설명입니다');

SELECT * FROM Shop_goods;